// No traduzco todas; solo las que se utilizan:
// jq '.Labels[].Name' *.json | sort | uniq
const labels = {
  Aardvark: 'Oso hormiguero',
  Abies: 'Pinos',
  Absinthe: 'Ajenjo',
  Abyssinian: 'Abisinio',
  Acanthaceae: 'Acanthaceae',
  Accessories: 'Accesorios',
  Accessory: 'Accesorio',
  Accipiter: 'Accipiter',
  Accordion: 'Acordeón',
  Acorn: 'Bellota',
  Acrobatic: 'Acrobático',
  Adapter: 'Adaptador',
  Adventure: 'Aventura',
  Advertisement: 'Anuncio',
  'Aerial View': 'Vista aérea',
  Affenpinscher: 'Affenpinscher',
  'Afghan Hound': 'Sabueso afgano',
  'African Grey Parrot': 'Loro gris africano',
  Aftershave: 'Aftershave',
  Agapanthus: 'Agapanto',
  Agaric: 'Agárico',
  Agate: 'Ágata',
  Agavaceae: 'Agaváceas',
  Agelaius: 'Agelayo',
  Agriculture: 'Agricultura',
  Agropyron: 'Agropiron',
  'Air Conditioner': 'Aire acondicionado',
  'Aircraft Carrier': 'Portaaviones',
  Aircraft: 'Aeronave',
  Airedale: 'Airedale',
  Airfield: 'Aeródromo',
  Airliner: 'Avión de línea',
  Airmail: 'Correo aéreo',
  Airplane: 'Avión',
  'Airport Terminal': 'Terminal de aeropuerto',
  Airport: 'Aeropuerto',
  Airship: 'Dirigible',
  Aisle: 'Pasillo',
  'Alarm Clock': 'Despertador',
  Albatross: 'Albatros',
  Alcohol: 'Alcohol',
  Alcyonacea: 'Alcionácea',
  Algae: 'Algas',
  Alien: 'Extraterrestre',
  Alley: 'Callejón',
  Alleyway: 'Callejón',
  Alligator: 'Caimán',
  Allium: 'Alio',
  'Alloy Wheel': 'Rueda de aleación',
  Almond: 'Almendra',
  Aloe: 'Áloe',
  Alpaca: 'Alpaca',
  Alphabet: 'Alfabeto',
  Altar: 'Altar',
  Aluminium: 'Aluminio',
  Amanita: 'Amanita',
  Amaranthaceae: 'Amaranthaceae',
  Amaryllidaceae: 'Amarilidáceas',
  Amaryllis: 'Amarilis',
  Ambulance: 'Ambulancia',
  'American Flag': 'Bandera de Estados Unidos',
  'American Football': 'Fútbol americano',
  Amethyst: 'Amatista',
  Ammunition: 'Munición',
  Ampersand: 'Y comercial',
  Amphibian: 'Anfibio',
  'Amphibious Vehicle': 'Vehículo anfibio',
  Amphiprion: 'Anfiprión',
  Amphitheater: 'Anfiteatro',
  Amphitheatre: 'Anfiteatro',
  Amplifier: 'Amplificador',
  'Amusement Park': 'Parque de atracciones',
  Anaconda: 'Anaconda',
  'Analog Clock': 'Reloj analógico',
  Anchor: 'Ancla',
  'Andalusian Horse': 'Caballo Andaluz',
  Andrena: 'Abeja andrena',
  Anemone: 'Anémona',
  Angel: 'Ángel',
  Angelfish: 'Pez ángel',
  Angler: 'Pescador de caña',
  Angora: 'Angora',
  Angus: 'Angus',
  Anhinga: 'Anhinga',
  Animal: 'Animal',
  Anise: 'Anís',
  Anisoptera: 'Anisópteros',
  Ankle: 'Tobillo',
  Anklet: 'Tobillera',
  Annonaceae: 'Annonaceae',
  Anole: 'Anolis',
  Anseriformes: 'Anseriformes',
  Ant: 'Hormiga',
  Anteater: 'Oso hormiguero',
  Antelope: 'Antílope',
  Antenna: 'Antena',
  Anther: 'Antera',
  Anthracite: 'Antracita',
  Anthurium: 'Anturio',
  Anthus: 'Anthus',
  'Antique Car': 'Coche antiguo',
  Antler: 'Astas',
  Anvil: 'Yunque',
  'Apartment Building': 'Edificio de pisos',
  Ape: 'Simio',
  Aphid: 'Áfido',
  Apiaceae: 'Apiáceas',
  Apiary: 'Colmenar',
  Apidae: 'Ápidos',
  Apparel: 'Vestimenta',
  Appenzeller: 'Appenzeller',
  'Apple Pie': 'Pie de manzana',
  Apple: 'Manzana',
  Appliance: 'Aparato',
  Applique: 'Apliques',
  Apricot: 'Albaricoque',
  Apron: 'Delantal',
  Apse: 'Ábside',
  'Aqua Scuba': 'Buceo',
  Aquarium: 'Acuario',
  Aquatic: 'Acuático',
  Aquilegia: 'Aquilegia',
  Araceae: 'Aráceas',
  Arachnid: 'Arácnido',
  Arbour: 'Cenador',
  'Arcade Game Machine': 'Máquina de juegos de arcade',
  'Arch Bridge': 'Puente de arco',
  Arch: 'Arco',
  Archaeology: 'Arqueología',
  Archangel: 'Arcángel',
  Arched: 'Arqueado',
  Archer: 'Arquero',
  Archery: 'Tiro al arco',
  Architecture: 'Arquitectura',
  'Arctic Fox': 'Zorro ártico',
  Ardeidae: 'Ardeidas',
  Arecaceae: 'Arecáceas',
  Arena: 'Pabellón',
  Arenaria: 'Arenaría',
  Argiope: 'Argiope',
  Arm: 'Brazo',
  Armadillo: 'Armadillo',
  Armchair: 'Sillón',
  Armor: 'Armadura',
  Armored: 'Blindado',
  Armory: 'Arsenal',
  Army: 'Ejército',
  Arrow: 'Flecha',
  Arrowhead: 'Punta de flecha',
  'Art Gallery': 'Galería de arte',
  Art: 'Arte',
  Artichoke: 'Alcachofa',
  Arugula: 'Rúcula',
  Ashtray: 'Cenicero',
  Asilidae: 'Asilidos',
  Asleep: 'Dormido',
  Asparagus: 'Espárrago',
  Asphalt: 'Asfalto',
  'Assembly Line': 'Linea de montaje',
  Aster: 'Aster',
  Asteraceae: 'Asteráceas',
  Astragalus: 'Astrágalo',
  Astronaut: 'Astronauta',
  Astronomy: 'Astronomía',
  Athlete: 'Atleta',
  Atlas: 'Atlas',
  Atm: 'Cajero automático',
  Atoll: 'Atolón',
  Attic: 'Ático',
  Attorney: 'Abogado',
  Atv: 'Vehículo todoterreno',
  Audience: 'Audiencia',
  'Audio Speaker': 'Altavoz de sonido',
  Auditorium: 'Auditorio',
  Aurora: 'Aurora',
  Autograph: 'Autógrafo',
  Automobile: 'Coche',
  Avalanche: 'Avalancha',
  Avocado: 'Aguacate',
  Awning: 'Toldo',
  Axe: 'Hacha',
  Axle: 'Eje',
  'Azure Sky': 'Cielo azul',
  Baboon: 'Babuino',
  Baby: 'Bebé',
  Back: 'Atrás',
  Backpack: 'Mochila',
  Backyard: 'Patio interior',
  Bacon: 'Tocino',
  Badge: 'Distintivo',
  Badger: 'Tejón',
  Badminton: 'Bádminton',
  Bag: 'Bolso',
  Bagel: 'Rosquilla',
  Bagpipe: 'Gaita',
  Bait: 'Carnada',
  Bakery: 'Panadería',
  'Balance Beam': 'Barra de equilibrio',
  Balcony: 'Balcón',
  'Bald Eagle': 'Águila calva',
  Ball: 'Pelota',
  Ballerina: 'Bailarina',
  Ballet: 'Ballet',
  Balloon: 'Globo',
  Ballplayer: 'Jugador de béisbol',
  Ballroom: 'Salón de baile',
  'Bamboo Shoot': 'Brote de bambú',
  Bamboo: 'Bambú',
  'Banana Boat': 'Barco hinchable',
  Banana: 'Plátano',
  Bandage: 'Vendaje',
  Bandana: 'Pañuelo',
  Bangles: 'Brazaletes',
  Banister: 'Barandilla',
  Banjo: 'Banjo',
  Banner: 'Estandarte',
  'Bar Counter': 'Barra de bar',
  'Bar Stool': 'Taburete de bar',
  'Barbed Wire': 'Alambre de espino',
  Barbie: 'Barbie',
  Barefoot: 'Descalzo',
  Barge: 'Barcaza',
  Barn: 'Granero',
  Barrel: 'Barril',
  Barricade: 'Barricada',
  Barrow: 'Carretilla',
  Bartender: 'Barman',
  'Baseball Bat': 'Bate de béisbol',
  'Baseball Cap': 'Gorra de béisbol',
  'Baseball Field': 'Campo de béisbol',
  'Baseball Glove': 'Guante de béisbol',
  Baseball: 'Béisbol',
  Basement: 'Sótano',
  Basin: 'Lavabo',
  Basket: 'Cesta',
  'Basketball Court': 'Cancha de baloncesto',
  Basketball: 'Baloncesto',
  'Bass Guitar': 'Bajo',
  Bat: 'Murciélago',
  'Bath Towel': 'Toalla de baño',
  'Bathing Cap': 'Gorro de baño',
  Bathroom: 'Baño',
  Bathtub: 'Bañera',
  'Batman Logo': 'Logotipo de Batman',
  Batman: 'Batman',
  Baton: 'Batuta',
  'Batting Helmet': 'Casco de bateo',
  Battleship: 'Acorazado',
  Bay: 'Bahía',
  Bazaar: 'Bazar',
  Bbq: 'Barbacoa',
  'Beach Wagon': 'Vagón de playa',
  Beach: 'Playa',
  Beacon: 'Faro',
  'Bead Necklace': 'Collar de cuentas',
  Bead: 'Cuenca',
  Beagle: 'Beagle',
  Beak: 'Pico',
  'Bean Sprout': 'Brotes de soja',
  Bean: 'Judía',
  Beanie: 'Gorro',
  Bear: 'Oso',
  Beard: 'Barba',
  Beaver: 'Castor',
  Bed: 'Cama',
  Bedroom: 'Dormitorio',
  'Bee Eater': 'Abejaruco',
  Bee: 'Abeja',
  'Beer Bottle': 'Botella de cerveza',
  'Beer Glass': 'Vaso de cerveza',
  Beer: 'Cerveza',
  'Bell Pepper': 'Pimiento morrón',
  'Bell Tower': 'Campanario',
  Belt: 'Cinturón',
  'Beluga Whale': 'Ballena beluga',
  Bench: 'Banco',
  Beverage: 'Bebida',
  Bib: 'Babero',
  Bicycle: 'Bicicleta',
  Bike: 'Bicicleta',
  Bikini: 'Bikini',
  Billboard: 'Cartelera',
  'Billiard Room': 'Sala de billar',
  Binoculars: 'Prismáticos',
  Biplane: 'Biplano',
  Birch: 'Abedul',
  'Bird Feeder': 'Comedero para pájaros',
  'Bird Nest': 'Nido',
  Bird: 'Pájaro',
  'Birthday Cake': 'Tarta de cumpleaños',
  'Birthday Party': 'Fiesta de cumpleaños',
  Biscuit: 'Galleta',
  Bishop: 'Obispo',
  Bison: 'Bisonte',
  'Black Bear': 'Oso negro',
  'Black Cat': 'Gato negro',
  'Black Hair': 'Pelo negro',
  'Black Swan': 'Cisne negro',
  'Black Widow': 'Viuda negra',
  Blackbird: 'Mirlo',
  Blackboard: 'Pizarra',
  Blade: 'Hoja',
  Blanket: 'Manta',
  Blazer: 'Americana',
  Blender: 'Licuadora',
  Blimp: 'Dirigible',
  Blizzard: 'Tormenta de nieve',
  Blonde: 'Rubio',
  Blossom: 'Flor',
  Blouse: 'Blusa',
  'Blow Dryer': 'Secador de pelo',
  'Blue Jay': 'Arrendajo azul',
  Blueberry: 'Arándano',
  Bluebird: 'Azulejo',
  Bmx: 'Bici de montaña',
  Boar: 'Jabalí',
  Boardwalk: 'Paseo marítimo',
  Boat: 'Bote',
  Bobsled: 'Bobsleigh',
  Bog: 'Pantano',
  Boiling: 'Hirviendo',
  Bomb: 'Bomba',
  Bomber: 'Bombardero',
  Bonfire: 'Hoguera',
  Bongo: 'Bongo',
  Bonito: 'Bonito',
  Bonnet: 'Sombrero',
  Bonsai: 'Bonsái',
  Booby: 'Bobo',
  Book: 'Libro',
  Bookcase: 'Librero',
  Bookstore: 'Librería',
  Boot: 'Bota',
  'Boston Bull': 'Boston terrier',
  Bottle: 'Botella',
  Boutique: 'Boutique',
  'Bow Tie': 'Pajarita',
  Bow: 'Arco',
  Bowl: 'Bol',
  'Bowling Ball': 'Bola de bolos',
  Bowling: 'Bolos',
  'Box Turtle': 'Tortuga',
  Box: 'Caja',
  Boxer: 'Boxer',
  Boxing: 'Boxeo',
  Boy: 'Chico',
  Bra: 'Sujetador',
  Brace: 'Abrazadera',
  Bracelet: 'Pulsera',
  Bracket: 'Soporte',
  Braid: 'Trenza',
  'Brain Coral': 'Coral',
  Brake: 'Freno',
  'Brass Section': 'Sección de metales',
  'Bread Loaf': 'Hogaza de pan',
  Bread: 'Pan',
  Breakfast: 'Desayuno',
  Brewery: 'Cervecería',
  Brick: 'Ladrillo',
  Bride: 'Novia',
  Bridegroom: 'Novio',
  Bridesmaid: 'Dama de honor',
  Bridge: 'Puente',
  Brie: 'Queso brie',
  Briefcase: 'Maletín',
  Broccoli: 'Brócoli',
  Brochure: 'Folleto',
  Bronze: 'Bronce',
  Brooch: 'Broche',
  Broom: 'Escoba',
  'Brown Bear': 'Oso pardo',
  Brownie: 'Brownie',
  Brush: 'Cepillo',
  Bubble: 'Burbuja',
  Bucket: 'Cubo',
  Buckle: 'Hebilla',
  Bud: 'Brote',
  Buddha: 'Buda',
  Buffalo: 'Búfalo',
  Buffet: 'Bufé',
  Buggy: 'Carrito',
  Bugle: 'Bugle',
  Building: 'Edificio',
  Bull: 'Toro',
  Bulldog: 'Buldog',
  Bulldozer: 'Excavadora',
  'Bullet Train': 'Tren bala',
  Bullet: 'Bala',
  Bullfighter: 'Torero',
  Bullfighting: 'Toreo',
  Bullring: 'Plaza de toros',
  Bumblebee: 'Abejorro',
  Bumper: 'Parachoque',
  Bun: 'Bollo',
  Bungee: 'Cuerda elástica',
  'Bunk Bed': 'Litera',
  Bunker: 'Búnker',
  Bunny: 'Conejito',
  Burger: 'Hamburguesa',
  Burner: 'Quemador',
  Burrito: 'Burrito',
  'Bus Stop': 'Parada de autobús',
  Bus: 'Autobús',
  Bush: 'Arbusto',
  'Business Card': 'Tarjeta de visita',
  'Butcher Shop': 'Carnicería',
  Butter: 'Mantequilla',
  Butterfly: 'Mariposa',
  Buzzard: 'Buitre',
  Cab: 'Taxi',
  Cabbage: 'Repollo',
  Cabin: 'Cabina',
  Cabinet: 'Gabinete',
  'Cable Car': 'Teleférico',
  Cable: 'Cable',
  Cactus: 'Cactus',
  Cafe: 'Cafetería',
  Cafeteria: 'Cafetería',
  Cake: 'Pastel',
  Calculator: 'Calculadora',
  Calendar: 'Calendario',
  Calf: 'Becerro',
  Calligraphy: 'Caligrafía',
  Camel: 'Camello',
  'Camera Lens': 'Lente de la cámara',
  Camera: 'Cámara',
  Camouflage: 'Camuflaje',
  Camping: 'Cámping',
  Campus: 'Campus',
  'Can Opener': 'Abrelatas',
  Can: 'Lata',
  Canal: 'Canal',
  Canary: 'Canario',
  Candle: 'Vela',
  Candy: 'Caramelo',
  Cane: 'Caña',
  Canine: 'Canino',
  'Canned Goods': 'Productos enlatados',
  Cannon: 'Cañón',
  Canoe: 'Canoa',
  Canopy: 'Dosel',
  Canvas: 'Lienzo',
  Canyon: 'Cañón',
  Cap: 'Gorra',
  Cape: 'Capa',
  Capsule: 'Cápsula',
  Captain: 'Capitán',
  'Car Dealership': 'Concesionario de coches',
  'Car Mirror': 'Espejo retrovisor',
  'Car Seat': 'Asiento de coche',
  'Car Show': 'Exposición de coches',
  'Car Trunk': 'Maletero',
  'Car Wash': 'Lavado de coches',
  'Car Wheel': 'Llanta de coche',
  Car: 'Coche',
  Caramel: 'Caramelo',
  Caravan: 'Caravana',
  Cardboard: 'Cartón',
  Cardigan: 'Cárdigan',
  Cardinal: 'Cardenal',
  Cargo: 'Carga',
  Carnation: 'Clavel',
  Carnival: 'Carnaval',
  Carousel: 'Carrusel',
  Carp: 'Carpa',
  Carpenter: 'Carpintero',
  Carriage: 'Carruaje',
  Carrot: 'Zanahoria',
  Carton: 'Caja de cartón',
  'Cash Machine': 'Cajero automático',
  'Cassette Player': 'Reproductor de casete',
  Cassette: 'Casete',
  Castle: 'Castillo',
  Cat: 'Gato',
  Cathedral: 'Catedral',
  Cattle: 'Ganado',
  Cauliflower: 'Coliflor',
  Cave: 'Cueva',
  'Cd Player': 'Reproductor de CD',
  'Ceiling Fan': 'Ventilador de techo',
  'Ceiling Light': 'Lámpara de techo',
  'Cell Phone': 'Teléfono móvil',
  Cello: 'Violonchelo',
  'Chain Mail': 'Cota de malla',
  'Chain Saw': 'Motosierra',
  Chain: 'Cadena',
  Chair: 'Silla',
  Chandelier: 'Candelabro',
  Cheetah: 'Guepardo',
  Chef: 'Cocinero',
  'Cherry Blossom': 'Flor de cerezo',
  Cherry: 'Cereza',
  Chess: 'Ajedrez',
  Chicken: 'Pollo',
  Chihuahua: 'Chihuahua',
  Child: 'Niño',
  Chime: 'Campanilla',
  'China Cabinet': 'Vitrina',
  Chinchilla: 'Chinchilla',
  Chocolate: 'Chocolate',
  Chow: 'Chow chow',
  'Christmas Stocking': 'Calcetín navideño',
  'Christmas Tree': 'Árbol de Navidad',
  Church: 'Iglesia',
  Cinema: 'Cine',
  Circus: 'Circo',
  'Citrus Fruit': 'Fruta cítrica',
  City: 'Ciudad',
  Clam: 'Almeja',
  Clamp: 'Abrazadera',
  Clarinet: 'Clarinete',
  Classroom: 'Aula',
  Claw: 'Garra',
  Cleaning: 'Limpieza',
  Cliff: 'Acantilado',
  Climbing: 'Escalada',
  Clinic: 'Clínica',
  Cloak: 'Capa',
  'Clock Tower': 'Torre de reloj',
  Clock: 'Reloj',
  Clogs: 'Zuecos',
  Closet: 'Armario',
  'Clothes Iron': 'Plancha de ropa',
  Clothing: 'Ropa',
  Cloud: 'Nube',
  Clown: 'Payaso',
  Club: 'Club',
  'Clutch Wheel': 'Rueda de embrague',
  Coal: 'Carbón',
  'Coast Guard': 'Guardacostas',
  Coast: 'Costa',
  Coaster: 'Portavasos',
  'Coat Rack': 'Perchero',
  Coat: 'Abrigo',
  Cobblestone: 'Adoquín',
  Cobra: 'Cobra',
  Coca: 'Coca',
  'Cock Bird': 'Gallo',
  Cockatoo: 'Cacatúa',
  'Cocker Spaniel': 'Cocker spaniel',
  Cockpit: 'Cabina',
  Cockroach: 'Cucaracha',
  Cocktail: 'Cóctel',
  Cocoa: 'Cacao',
  Coconut: 'Coco',
  Cod: 'Bacalao',
  'Coffee Cup': 'Taza de café',
  'Coffee Table': 'Mesa de centro',
  Coho: 'Coho',
  Coil: 'Bobina',
  Coin: 'Moneda',
  Coke: 'Coca',
  Collage: 'Collage',
  Collar: 'Cuello',
  College: 'Universidad',
  Collie: 'Collie',
  'Colt Horse': 'Potro',
  Column: 'Columna',
  Comb: 'Peine',
  'Combination Lock': 'Cerradura de combinación',
  Comet: 'Cometa',
  Comics: 'Historietas',
  'Compass Math': 'Compás',
  Compass: 'Brújula',
  'Computer Hardware': 'Hardware de la computadora',
  'Computer Keyboard': 'Teclado',
  Computer: 'Ordenador',
  Concert: 'Concierto',
  Conch: 'Concha',
  Concrete: 'Hormigón',
  Condo: 'Apartamento',
  Condor: 'Cóndor',
  Cone: 'Cono',
  Confectionery: 'Confitería',
  'Conference Room': 'Sala de conferencias',
  Confetti: 'Confeti',
  Conga: 'Conga',
  Conifer: 'Conífera',
  'Construction Crane': 'Grúa de construcción',
  Construction: 'Construcción',
  'Contact Lens': 'Lentes de contacto',
  'Control Tower': 'Torre de control',
  'Convention Center': 'Centro de Convenciones',
  Convertible: 'Convertible',
  Cooker: 'Horno',
  Cookie: 'Galleta',
  'Cooking Batter': 'Masa de cocina',
  Cooktop: 'Placa de cocina',
  Cooler: 'Enfriador',
  'Coral Reef': 'Arrecife de coral',
  Cork: 'Corcho',
  Cormorant: 'Cormorán',
  Corn: 'Maíz',
  Cornbread: 'Pan de maíz',
  Corner: 'Esquina',
  Cornet: 'Cucurucho',
  Corridor: 'Corredor',
  Corset: 'Corsé',
  Cosmetics: 'Productos cosméticos',
  Cosplay: 'Cosplay',
  Costume: 'Traje',
  Cottage: 'Cabaña',
  Cotton: 'Algodón',
  Couch: 'Sofá',
  Cougar: 'Puma',
  Countryside: 'Campo',
  Coupe: 'Cupé',
  Court: 'Corte',
  Cove: 'Ensenada',
  Cow: 'Vaca',
  Cowbell: 'Cencerro',
  'Cowboy Boot': 'Bota de vaquero',
  'Cowboy Hat': 'Sombrero de vaquero',
  Coyote: 'Coyote',
  Cpu: 'CPU',
  Crab: 'Cangrejo',
  Cracker: 'Galleta',
  Cradle: 'Cuna',
  'Crane Bird': 'Pájaro grulla',
  'Crash Helmet': 'Casco protector',
  Crate: 'Caja',
  Crater: 'Cráter',
  Crawdad: 'Cangrejo de río',
  Crawling: 'A gatas',
  Crayon: 'Lápiz de color',
  Cream: 'Crema',
  'Credit Card': 'Tarjeta de crédito',
  Creek: 'Arroyo',
  Creme: 'Crema',
  Crib: 'Cuna',
  'Cricket Insect': 'Grillo',
  Cricket: 'Grillo',
  Crocodile: 'Cocodrilo',
  Crocus: 'Azafrán',
  Croissant: 'Cruasán',
  Croquet: 'Juego de croquet',
  'Cross Country': 'A campo traviesa',
  Cross: 'Cruz',
  'Crossword Puzzle': 'Crucigrama',
  Crow: 'Cuervo',
  Crowd: 'Multitud',
  Crown: 'Corona',
  Crucifix: 'Crucifijo',
  'Cruise Ship': 'Crucero',
  Cruiser: 'Crucero',
  Crypt: 'Cripta',
  Crystal: 'Cristal',
  'Ct Scan': 'Tomografía computerizada',
  Cucumber: 'Pepino',
  Cuff: 'Brazalete',
  Culinary: 'Culinario',
  Cumulus: 'Cúmulo',
  Cup: 'Taza',
  Cupboard: 'Alacena',
  Cupcake: 'Magdalena',
  Cupid: 'Cupido',
  Curling: 'Curling',
  Curry: 'Curry',
  Curtain: 'Cortina',
  Cushion: 'Almohadón',
  Custard: 'Flan',
  Cutlery: 'Cubiertos',
  Cyclist: 'Ciclista',
  Cylinder: 'Cilindro',
  Daffodil: 'Narciso',
  Dagger: 'Daga',
  Dahlia: 'Dalia',
  'Dairy Cow': 'Vaca lechera',
  Dairy: 'Lácteos',
  Daisies: 'Margaritas',
  Daisy: 'Margarita',
  Dalmatian: 'Dálmata',
  Dam: 'Presa',
  'Dance Pose': 'Paso de baile',
  Dance: 'Baile',
  Dandelion: 'Diente de león',
  Darts: 'Dardos',
  Dating: 'Cita',
  Dawn: 'Amanecer',
  Debate: 'Debate',
  Deck: 'Plataforma',
  Deer: 'Ciervo',
  Deli: 'Delicatessen',
  Demolition: 'Demolición',
  Den: 'Guarida',
  Denim: 'Vaquero',
  Dentist: 'Dentista',
  Deodorant: 'Desodorante',
  Desert: 'Desierto',
  Desk: 'Escritorio',
  Desktop: 'Escritorio',
  Dessert: 'Postre',
  Destroyer: 'Destructor',
  Device: 'Dispositivo',
  Diagram: 'Diagrama',
  'Dial Telephone': 'Teléfono de dial',
  Diamond: 'Diamante',
  Diaper: 'Pañal',
  Diary: 'Diario',
  Dice: 'Dado',
  'Digital Camera': 'Cámara digital',
  'Digital Clock': 'Reloj digital',
  'Digital Watch': 'Reloj digital',
  Dill: 'Eneldo',
  Dime: 'Moneda',
  Dimples: 'Hoyuelos',
  Diner: 'Cafetería',
  Dinghy: 'Bote',
  'Dining Room': 'Comedor',
  'Dining Table': 'Mesa de comedor',
  Dinner: 'Cena',
  Dinosaur: 'Dinosaurio',
  Dip: 'Salsa',
  Diploma: 'Diploma',
  'Dirt Road': 'Camino de tierra',
  Disco: 'Disco',
  Dish: 'Plato',
  Dishwasher: 'Lavaplatos',
  Disk: 'Disco',
  Display: 'Mostrar',
  Ditch: 'Abandone',
  Diver: 'Buzo',
  Diving: 'Buceo',
  Diwali: 'Día de la Independencia',
  Dj: 'DJ',
  Dock: 'Muelle',
  Doctor: 'Doctor',
  Document: 'Documento',
  Dodo: 'Dodo',
  'Dog House': 'Caseta de perro',
  Dog: 'Perro',
  Dogsled: 'Trineo de perros',
  Doll: 'Muñeca',
  Dollar: 'Dólar',
  Dolphin: 'Delfín',
  Dome: 'Domo',
  Domino: 'Dominó',
  Donkey: 'Burro',
  Donut: 'Rosquilla',
  Doodle: 'Esbozo',
  Door: 'Puerta',
  Doormat: 'Felpudo',
  'Dorm Room': 'Dormitorio',
  'Double Decker Bus': 'Autobús de dos pisos',
  'Double Sink': 'Fregadero doble',
  Dough: 'Masa',
  Dove: 'Paloma',
  Downtown: 'Centro',
  Dragon: 'Dragón',
  Dragonfly: 'Libélula',
  Drain: 'Desagüe',
  Drawbridge: 'Puente levadizo',
  Drawer: 'Cajón',
  Drawing: 'Dibujo',
  Dredger: 'Draga',
  'Dress Shirt': 'Camisa de vestir',
  Dress: 'Vestido',
  Dresser: 'Vestidor',
  'Dressing Room': 'Vestidor',
  Driftwood: 'Madera flotante',
  Drink: 'Bebida',
  'Drinking Fountain': 'Fuente de agua',
  Drinking: 'Bebida',
  'Drive Shaft': 'Eje de accionamiento',
  'Driving License': 'Carné de conducir',
  Driving: 'Conduciendo',
  Droplet: 'Gotita',
  Drum: 'Tambor',
  Drummer: 'Batería',
  Dryer: 'Secadora',
  'Drying Rack': 'Tendedero',
  Duck: 'Pato',
  Duel: 'Duelo',
  Duet: 'Dueto',
  Dugout: 'Refugio subterráneo',
  Dumpling: 'Bola de masa hervida',
  Dune: 'Duna',
  'Dung Beetle': 'Escarabajo pelotero',
  Dungeon: 'Calabozo',
  Durian: 'Durián',
  Dusk: 'Atardecer',
  'Dutch Oven': 'Horno holandés',
  Dvd: 'DVD',
  Dye: 'Teñir',
  Dynamite: 'Dinamita',
  Eagle: 'Águila',
  Ear: 'Oído',
  Earring: 'Arete',
  Earth: 'Tierra',
  Earthquake: 'Terremoto',
  'Easter Egg': 'Huevo de Pascua',
  Eating: 'Comiendo',
  Eclipse: 'Eclipse',
  Eel: 'Anguila',
  Egg: 'Huevo',
  Eggplant: 'Berenjena',
  Egret: 'Garceta',
  'Egyptian Cat': 'Gato egipcio',
  'Electric Fan': 'Ventilador eléctrico',
  'Electric Guitar': 'Guitarra electrica',
  'Electric Transmission Tower': 'Torre eléctrica',
  'Electrical Device': 'Dispositivo eléctrico',
  'Electrical Outlet': 'Toma de corriente',
  'Electronic Chip': 'Chip electrónico',
  Electronics: 'Electrónica',
  Elephant: 'Elefante',
  Elevator: 'Ascensor',
  Elf: 'Duende',
  Elk: 'Alce',
  Emblem: 'Emblema',
  Embroidery: 'Bordado',
  Emerald: 'Esmeralda',
  Emu: 'Emú',
  Engine: 'Motor',
  'Entertainment Center': 'Centro de entretenimiento',
  Envelope: 'Sobre',
  Equestrian: 'Ecuestre',
  Eruption: 'Erupción',
  'Eskimo Dog': 'Perro esquimal',
  Espresso: 'Café exprés',
  Euphonium: 'Bombardino',
  'Evening Dress': 'Vestido de noche',
  Executive: 'Ejecutivo',
  Exercise: 'Ejercicio',
  'Face Makeup': 'Maquillaje facial',
  Face: 'Rostro',
  Factory: 'Fábrica',
  Family: 'Familia',
  'Farm Plow': 'Arado de granja',
  Farm: 'Granja',
  Fashion: 'Moda',
  'Feather Boa': 'Boa de plumas',
  Female: 'Femenino',
  Fence: 'Cerca',
  Fencing: 'Esgrima',
  Fern: 'Helecho',
  Ferret: 'Hurón',
  'Ferris Wheel': 'Noria',
  Ferry: 'Ferri',
  Festival: 'Festival',
  Fiddle: 'Violín',
  Field: 'Campo',
  Fig: 'Higo',
  Figurine: 'Figurilla',
  'File Binder': 'Archivador',
  'File Folder': 'Carpeta de archivos',
  File: 'Archivo',
  Finch: 'Pinzón',
  Finger: 'Dedo',
  Fir: 'Abeto',
  'Fire Department': 'Cuerpo de bomberos',
  'Fire Hydrant': 'Boca de incendio',
  'Fire Screen': 'Pantalla de fuego',
  'Fire Truck': 'Camión de bomberos',
  Fire: 'Fuego',
  Firefly: 'Luciérnaga',
  Fireman: 'Bombero',
  Fireplace: 'Chimenea',
  Fireworks: 'Fuegos artificiales',
  'First Aid': 'Primeros auxilios',
  Fish: 'Pescado',
  Fisheye: 'Ojo de pez',
  'Fishing Lure': 'Cebo de pesca',
  Fishing: 'Pesca',
  Fist: 'Puño',
  Fitness: 'Aptitud física',
  Flag: 'Bandera',
  Flagstone: 'Losa',
  Flame: 'Fuego',
  Flamenco: 'Flamenco',
  Flamingo: 'Flamenco',
  Flare: 'Llamarada',
  Flashlight: 'Linterna',
  Flax: 'Linaza',
  Flea: 'Pulga',
  Fleece: 'Lana',
  'Flicker Bird': 'Pájaro carpintero',
  Flight: 'Vuelo',
  'Flip-Flop': 'Chanclas',
  Flock: 'Rebaño',
  Flood: 'Inundación',
  'Floor Plan': 'Plano de planta',
  Floor: 'Piso',
  Flooring: 'Piso',
  'Floral Design': 'Diseño floral',
  Flounder: 'Platija',
  Flour: 'Harina',
  'Flower Arrangement': 'Arreglo floral',
  'Flower Bouquet': 'Ramo de flores',
  Flower: 'Flor',
  Flugelhorn: 'Fliscorno',
  Flute: 'Flauta',
  Fly: 'Mosca',
  Flyer: 'Folleto',
  Flying: 'Volador',
  Foal: 'Potro',
  Foam: 'Espuma',
  Fog: 'Niebla',
  Foil: 'Papel de aluminio',
  'Folding Door': 'Puerta plegable',
  Fondue: 'Fondue',
  'Food Court': 'Zona de comidas',
  Food: 'Alimento',
  'Football Field': 'Campo de fútbol',
  'Football Helmet': 'Casco de fútbol',
  Football: 'Fútbol',
  Footprint: 'Huella',
  Footwear: 'Calzado',
  'Forest Fire': 'Incendio forestal',
  Forest: 'Bosque',
  Forge: 'Fragua',
  Fork: 'Tenedor',
  'Formula One': 'Fórmula 1',
  Fort: 'Fuerte',
  Fossil: 'Fósil',
  'Fountain Pen': 'Pluma fuente',
  Fountain: 'Fuente',
  Fowl: 'Ave',
  Fox: 'Zorro',
  Foxglove: 'Dedalera',
  Fractal: 'Fractal',
  Freckle: 'Peca',
  Freeway: 'Autopista',
  'Freight Car': 'Vagón de carga',
  Freighter: 'Buque de carga',
  'French Bulldog': 'Bulldog francés',
  'French Door': 'Puerta francesa',
  'French Horn': 'Trompa',
  'French Loaf': 'Baguette',
  'French Toast': 'Tostada francesa',
  'Fried Chicken': 'Pollo frito',
  Fries: 'Patatas fritas',
  Frisbee: 'Disco volador',
  Frog: 'Rana',
  Frost: 'Escarcha',
  Frown: 'Fruncir el ceño',
  Fruit: 'Fruta',
  'Frying Pan': 'Sartén',
  Fudge: 'Dulce de azúcar',
  'Full Moon': 'Luna llena',
  Funeral: 'Funeral',
  Fungus: 'Hongo',
  Fur: 'Piel',
  Furniture: 'Muebles',
  Fuse: 'Fusible',
  Gambling: 'Juego',
  Game: 'Juego',
  Garage: 'Garaje',
  'Garden Spider': 'Araña de jardín',
  'Garden Umbrella': 'Sombrilla de jardín',
  Garden: 'Jardín',
  Gardener: 'Jardinero',
  Gardening: 'Jardinería',
  Gargoyle: 'Gárgola',
  Garlic: 'Ajo',
  'Gas Pump': 'Bomba de gas',
  'Gas Station': 'Gasolinera',
  'Gas Stove': 'Estufa de gas',
  Gate: 'Puerta',
  Gauge: 'Medir',
  Gazebo: 'Kiosko',
  Gazelle: 'Gacela',
  Gear: 'Engranaje',
  Gearshift: 'Palanca de cambios',
  Gecko: 'Geco',
  Gemstone: 'Piedra preciosa',
  Generator: 'Generador',
  Geranium: 'Geranio',
  'German Shepherd': 'Pastor alemán',
  Geyser: 'Géiser',
  'Giant Panda': 'Panda gigante',
  Gift: 'Regalo',
  Gin: 'Ginebra',
  Ginger: 'Jengibre',
  Gingerbread: 'Pan de jengibre',
  Giraffe: 'Jirafa',
  Girl: 'Muchacha',
  Glacier: 'Glaciar',
  Gladiolus: 'Gladiolo',
  Glass: 'Copa',
  Glasses: 'Gafas',
  Glider: 'Planeador',
  Gliding: 'Vuelo sin motor',
  Glitter: 'Brillantina',
  Globe: 'Globo',
  Glockenspiel: 'Glockenspiel',
  Glove: 'Guante',
  Goat: 'Cabra',
  Goblet: 'Copa',
  Goggles: 'Gafas de protección',
  'Gold Medal': 'Medalla de oro',
  Gold: 'Oro',
  'Golden Retriever': 'Perro perdiguero de oro',
  Goldfish: 'Pez dorado',
  'Golf Ball': 'Pelota de golf',
  'Golf Cart': 'Carrito de golf',
  'Golf Club': 'Club de Golf',
  'Golf Course': 'Campo de golf',
  Golf: 'Golf',
  Gondola: 'Góndola',
  Gong: 'Gong',
  Goose: 'Ganso',
  Gorilla: 'Gorila',
  Gourd: 'Calabaza',
  Gown: 'Vestido',
  GPS: 'GPS',
  Graduation: 'Graduación',
  Graffiti: 'Pintada',
  Grain: 'Grano',
  'Grand Piano': 'Piano de cola',
  Granite: 'Granito',
  Grapefruit: 'Toronja',
  Grapes: 'Uvas',
  Graphics: 'Gráficos',
  Grass: 'Césped',
  Grasshoper: 'Saltamontes',
  Grasshopper: 'Saltamontes',
  Grassland: 'Pradera',
  Gravel: 'Grava',
  Gravy: 'Salsa',
  Gray: 'Gris',
  Grazing: 'Pastoreo',
  'Great Dane': 'Gran Danés',
  'Great White Shark': 'Gran tiburón blanco',
  'Green Bean': 'Judías verdes',
  'Green Lizard': 'Lagartija verde',
  'Green Snake': 'Serpiente verde',
  'Green Tea': 'Té verde',
  Green: 'Verde',
  Greenhouse: 'Invernadero',
  'Greeting Card': 'Tarjeta de felicitación',
  Grenade: 'Granada',
  'Grey Fox': 'Zorro gris',
  Grille: 'Reja',
  'Grocery Store': 'Tienda de comestibles',
  Ground: 'Tierra',
  Grouse: 'Urogallo',
  Grove: 'Arboleda',
  'Guard Rail': 'Barandilla',
  Guard: 'Guardia',
  Guitar: 'Guitarra',
  Guitarist: 'Guitarrista',
  Gum: 'Chicle',
  Gun: 'Pistola',
  Gutter: 'Canal',
  Gym: 'Gimnasio',
  Gymnast: 'Gimnasta',
  Gymnastics: 'Gimnasia',
  Hacienda: 'Hacienda',
  Hacksaw: 'Sierra',
  Hail: 'Granizo',
  'Hair Drier': 'Secadora de pelo',
  'Hair Slide': 'Horquilla',
  Hair: 'Pelo',
  Haircut: 'Corte de pelo',
  Hairdresser: 'Peluquero',
  'Half Track': 'Vehículo semioruga',
  Halibut: 'Fletán',
  Hall: 'Pasillo',
  Halloween: 'Víspera de Todos los Santos',
  Halter: 'Cabestro',
  Ham: 'Jamón',
  Hammer: 'Martillo',
  Hammock: 'Hamaca',
  Hamster: 'Hámster',
  'Hand-Held Computer': 'Computadora de mano',
  Hand: 'Mano',
  Handbag: 'Bolso',
  Handball: 'Balonmano',
  Handgun: 'Pistola',
  Handle: 'Mango',
  Handrail: 'Barandilla',
  Handsaw: 'Sierra de mano',
  Handshake: 'Apretón de manos',
  Handwriting: 'Escritura',
  Hangar: 'Hangar',
  Hanger: 'Percha',
  Harbor: 'Puerto',
  'Hard Disk': 'Disco duro',
  Hardhat: 'Casco de seguridad',
  Hardware: 'Hardware',
  Hardwood: 'Madera dura',
  Hare: 'Liebre',
  Harmonica: 'Harmónica',
  Harness: 'Arnés',
  Harp: 'Arpa',
  Harvest: 'Cosecha',
  Hat: 'Sombrero',
  Hawk: 'Halcón',
  Hay: 'Heno',
  'Head Cabbage': 'Repollo',
  Head: 'Cabeza',
  Headband: 'Cinta para la cabeza',
  Headlight: 'Faro',
  Headphones: 'Auriculares',
  Headrest: 'Reposacabezas',
  Headset: 'Auriculares',
  Heart: 'Corazón',
  Hearth: 'Hogar',
  Heater: 'Calentador',
  Hedge: 'Seto',
  Hedgehog: 'Erizo',
  Heel: 'Tacón',
  Helicopter: 'Helicóptero',
  Helmet: 'Casco',
  Hemp: 'Cáñamo',
  Hen: 'Gallina',
  Henna: 'Alheña',
  Herbal: 'Herbario',
  Herbs: 'Hierbas',
  Herd: 'Rebaño',
  Heron: 'Garza',
  Herring: 'Arenque',
  Hibiscus: 'Hibisco',
  'High Heel': 'Tacón alto',
  'High Jump': 'Salto alto',
  'High Rise': 'Rascacielos',
  Highway: 'Carretera',
  Hiking: 'Senderismo',
  Hill: 'Colina',
  Hip: 'Cadera',
  Hippie: 'Hippy',
  Hippo: 'Hipopótamo',
  Hockey: 'Hockey',
  Hoe: 'Azada',
  Hog: 'Cerdo',
  'Holding Hands': 'Tomados de la mano',
  Hole: 'Agujero',
  'Home Decor': 'Decoración del hogar',
  'Home Theater': 'Cine en casa',
  'Honey Bee': 'Abeja melífera',
  Honey: 'Miel',
  Honeycomb: 'Panal',
  Hood: 'Capucha',
  Hoodie: 'Sudadera',
  Hook: 'Gancho',
  Hoop: 'Aro',
  Horizon: 'Horizonte',
  Horn: 'Cuerno',
  Hornet: 'Avispón',
  'Horse Cart': 'Coche de caballos',
  Horse: 'Caballo',
  Horseshoe: 'Herradura',
  Hose: 'Manguera',
  Hospital: 'Hospital',
  Hostel: 'Hostal',
  'Hot Air Balloon': 'Globo aerostático',
  'Hot Chocolate': 'Chocolate caliente',
  'Hot Dog': 'Hot dog',
  'Hot Pot': 'Olla caliente',
  'Hot Rod': 'Coche de carreras',
  'Hot Tub': 'Bañera de hidromasaje',
  Hotel: 'Hotel',
  Hound: 'Sabueso',
  Hourglass: 'Reloj de arena',
  House: 'Casa',
  Housing: 'Alojamiento',
  Hovercraft: 'Aerodeslizador',
  Hub: 'Centro',
  Hubcap: 'Tapacubos',
  Huddle: 'Grupo',
  Hug: 'Abrazo',
  Hula: 'Hula',
  Human: 'Humano',
  Hummingbird: 'Colibrí',
  Hunting: 'Caza',
  Hurdle: 'Obstáculo',
  Hurricane: 'Huracán',
  Husky: 'Fornido',
  Hut: 'Cabaña',
  Hydrant: 'Boca de aguas',
  Hydrofoil: 'Hidroala',
  Hyena: 'Hiena',
  'Ice Cream': 'Helado',
  'Ice Hockey': 'Hockey sobre hielo',
  'Ice Pop': 'Polo de hielo',
  'Ice Skating': 'Patinaje sobre hielo',
  Ice: 'Hielo',
  Iceberg: 'Iceberg',
  Icebreaker: 'Rompehielos',
  Icicle: 'Carámbano',
  Icing: 'Glaseado',
  'Id Cards': 'Documentos de identidad',
  Igloo: 'Iglú',
  Iguana: 'Iguana',
  Ikebana: 'Ikebana',
  Impala: 'Impala',
  Incense: 'Incienso',
  'Indoor Play Area': 'Área de juegos interior',
  Indoors: 'Interiores',
  Inflatable: 'Hinchable',
  Injection: 'Inyección',
  Injury: 'Lesión',
  'Ink Bottle': 'Botella de tinta',
  Inn: 'Posada',
  Insect: 'Insecto',
  'Interior Design': 'Diseño de interiores',
  Intersection: 'Intersección',
  Interview: 'Entrevista',
  Invertebrate: 'Invertebrado',
  Iphone: 'Iphone',
  'iPod Shuffle': 'iPod shuffle',
  Ipod: 'iPod',
  Iris: 'Iris',
  Iron: 'Hierro',
  Island: 'Isla',
  Ivory: 'Marfil',
  Ivy: 'Hiedra',
  Jacket: 'Chaqueta',
  Jackfruit: 'Jaca',
  Jacuzzi: 'Jacuzzi',
  Jade: 'Jade',
  'Jaguar Car': 'Coche Jaguar',
  Jaguar: 'Jaguar',
  Jam: 'Mermelada',
  Jar: 'Frasco',
  Jaw: 'Mandíbula',
  Jay: 'Arrendajo',
  Jeans: 'Vaqueros',
  Jeep: 'Todoterreno',
  Jelly: 'Gelatina',
  Jellyfish: 'Medusa',
  Jersey: 'Jersey',
  'Jet Ski': 'Moto acuática',
  Jet: 'Chorro',
  'Jewelry Store': 'Joyería',
  Jewelry: 'Joyas',
  'Jigsaw Puzzle': 'Rompecabezas',
  Jogging: 'Trotar',
  Joystick: 'Palanca de mando',
  Judge: 'Juez',
  Judo: 'Judo',
  Jug: 'Jarra',
  Juggling: 'Malabares',
  Juice: 'Jugo',
  Jungle: 'Selva',
  Jury: 'Jurado',
  Kale: 'Col rizada',
  Kangaroo: 'Canguro',
  Karaoke: 'Karaoke',
  Karate: 'Kárate',
  Kart: 'Kart',
  Kayak: 'Kayac',
  Keg: 'Barrilete',
  Kennel: 'Perrera',
  Ketchup: 'Salsa de tomate',
  Kettle: 'Tetera',
  Kettledrum: 'Timbal',
  Key: 'Llave',
  Keyboard: 'Teclado',
  Khaki: 'Caqui',
  Kicking: 'Patadas',
  Kid: 'Niño',
  'Killer Whale': 'Orca',
  Kilt: 'Falda escocesa',
  Kimono: 'Kimono',
  Kindergarten: 'Jardín de infancia',
  'King Crab': 'Cangrejo real',
  'King Penguin': 'Pingüino real',
  'King Snake': 'Serpiente Real',
  Kiosk: 'Quiosco',
  Kiss: 'Beso',
  Kissing: 'Besando',
  'Kit Fox': 'Zorro kit',
  'Kitchen Island': 'Isla de cocina',
  Kitchen: 'Cocina',
  'Kite Bird': 'Pájaro cometa',
  Kite: 'Cometa',
  Kitten: 'Gatito',
  'Kiwi Bird': 'Pájaro del kiwi',
  Kiwi: 'Kiwi',
  Knee: 'Rodilla',
  Kneeling: 'Arrodillado',
  Knife: 'Cuchillo',
  Knight: 'Caballero',
  Knitting: 'Tejido de punto',
  Knot: 'Nudo',
  Koala: 'Coala',
  Kohlrabi: 'Colinabo',
  Koi: 'Carpas kois',
  'Lab Coat': 'Bata de laboratorio',
  Lab: 'Laboratorio',
  Label: 'Etiqueta',
  'Labrador Retriever': 'Labrador retriever',
  Labyrinth: 'Laberinto',
  Lace: 'Cordón',
  Lady: 'Señora',
  Lager: 'Cerveza dorada',
  Lagoon: 'Laguna',
  Lake: 'Lago',
  'Lamp Post': 'Poste de luz',
  Lamp: 'Lámpara',
  Lampshade: 'Pantalla de lámpara',
  Land: 'Tierra',
  Landing: 'Aterrizaje',
  Landscape: 'Paisaje',
  Landslide: 'Deslizamiento de tierra',
  Lantern: 'Linterna',
  Laptop: 'Ordenador portátil',
  Larch: 'Alerce',
  Lasagna: 'Lasaña',
  Laser: 'Láser',
  'Latex Clothing': 'Ropa de látex',
  Lathe: 'Torno',
  Latte: 'Latte',
  Laughing: 'Risa',
  Launch: 'Lanzar',
  Laundry: 'Lavadero',
  Lava: 'Lava',
  Lavender: 'Lavanda',
  'Lawn Mower': 'Cortacésped',
  Lawn: 'Césped',
  'LCD Screen': 'Pantalla LCD',
  Leaf: 'Lámina',
  Leash: 'Correa',
  'Leather Jacket': 'Chaqueta de cuero',
  Lecture: 'Conferencia',
  LED: 'Led',
  Leek: 'Puerro',
  Lei: 'Ley',
  'Leisure Activities': 'Actividades de ocio',
  Lemon: 'Limón',
  Lemonade: 'Limonada',
  Lemur: 'Lémur',
  'Lens Cap': 'Tapa de la lente',
  Lentil: 'Lenteja',
  Leopard: 'Leopardo',
  'Lesser Panda': 'Panda menor',
  'Letter Opener': 'Abrecartas',
  Letter: 'Carta',
  Letterbox: 'Buzón',
  Lettuce: 'Lechuga',
  Library: 'Biblioteca',
  'License Plate': 'Placa',
  License: 'Licencia',
  'Life Buoy': 'Boya de vida',
  Lifejacket: 'Chaleco salvavidas',
  'Light Fixture': 'Lámpara',
  Light: 'Luz',
  Lightbulb: 'Bombilla',
  Lighter: 'Encendedor',
  Lighthouse: 'Faro',
  Lighting: 'Encendiendo',
  Lightning: 'Relámpago',
  Lilac: 'Lila',
  Lily: 'Lirio',
  Lime: 'Lima',
  Limestone: 'Caliza',
  Limo: 'Limusina',
  Linen: 'Lino',
  Lingerie: 'Lencería',
  Lion: 'León',
  Lip: 'Labio',
  Lipstick: 'Lápiz labial',
  Liquor: 'Espíritu',
  'Living Room': 'Sala',
  Lizard: 'Lagartija',
  Llama: 'Llama',
  Lobby: 'Vestíbulo',
  Lobster: 'Langosta',
  Lock: 'Cerrar con llave',
  Locker: 'Armario',
  Locket: 'Medallón',
  Locomotive: 'Locomotora',
  Loft: 'Desván',
  'Log Cabin': 'Cuarto de troncos',
  Logo: 'Logo',
  Lollipop: 'Chupete',
  'Long Jump': 'Salto largo',
  'Long Sleeve': 'Manga larga',
  Longhorn: 'Longhorn',
  Lotion: 'Loción',
  Luggage: 'Equipaje',
  Lumber: 'Tablas de madera',
  'Lunar Eclipse': 'Eclipse lunar',
  Lunch: 'Almuerzo',
  Lupin: 'Lupino',
  Lute: 'Laúd',
  Lynx: 'Lince',
  Lyre: 'Lira',
  Macaroni: 'Macarrones',
  Macaw: 'Guacamayo',
  'Machine Gun': 'Ametralladora',
  Machine: 'Máquina',
  Magazine: 'Revista',
  Magician: 'Mago',
  Magnifying: 'Aumentador',
  Magpie: 'Urraca',
  Mail: 'Correo',
  Mailbox: 'Buzón',
  'Make Out': 'Dar a entender',
  Mallard: 'Pato real',
  Mallet: 'Mazo',
  Mammal: 'Mamífero',
  Man: 'Hombre',
  Manatee: 'Manatí',
  Mandolin: 'Mandolina',
  Manga: 'Manga',
  Mango: 'Mango',
  Manhole: 'Agujero de hombre',
  Manicure: 'Manicura',
  Mannequin: 'Maniquí',
  Mansion: 'Mansión',
  'Manta Ray': 'Manta raya',
  Mantis: 'Mantis',
  Manufacturing: 'Fabricación',
  Manx: 'Gato manés',
  Map: 'Mapa',
  'Maple Leaf': 'Hoja de arce',
  Maple: 'Arce',
  Maraca: 'Maraca',
  Marathon: 'Maratón',
  Marble: 'Mármol',
  Marching: 'Marcha',
  'Mardi Gras': 'Mardi Gras',
  Marina: 'Puerto pequeño',
  Marker: 'Marcador',
  Market: 'Mercado',
  Maroon: 'Granate',
  Marsh: 'Pantano',
  'Martial Arts': 'Artes marciales',
  Martini: 'Vermú',
  Mascara: 'Máscara',
  Mascot: 'Mascota',
  'Mashed Potato': 'Puré de patatas',
  Mask: 'Máscara',
  Massage: 'Masaje',
  Mat: 'Estera',
  Mattock: 'Azadón',
  Mattress: 'Colchón',
  Mayonnaise: 'Mayonesa',
  Maze: 'Laberinto',
  Meadow: 'Prado',
  Meal: 'Comida',
  Measurements: 'Mediciones',
  'Measuring Cup': 'Taza de medida',
  'Meat Loaf': 'Pastel de carne',
  Meatball: 'Albóndiga',
  Mecca: 'La meca',
  'Medical Imaging X-Ray Film': 'Película de radiografía',
  Medication: 'Medicamento',
  'Medicine Chest': 'Botiquin',
  Meerkat: 'Suricata',
  'Meeting Room': 'Sala de Reuniones',
  Melon: 'Melón',
  Menu: 'Menú',
  Mesa: 'Colina baja',
  Metropolis: 'Metrópoli',
  Microphone: 'Micrófono',
  Microscope: 'Microscopio',
  Microwave: 'Microondas',
  'Military Uniform': 'Uniforme militar',
  Military: 'Militar',
  'Milk Can': 'Olla de leche',
  Milk: 'Leche',
  Milkshake: 'Batido',
  'Milky Way': 'Vía Láctea',
  Mime: 'Mímica',
  Mimosa: 'Mimosa',
  'Mineral Water': 'Agua mineral',
  Mineral: 'Mineral',
  'Mini Golf': 'Mini golf',
  Minibus: 'Microbús',
  Mining: 'Minería',
  Miniskirt: 'Minifalda',
  Mint: 'Menta',
  Mirror: 'Espejo',
  Missile: 'Misil',
  Mist: 'Neblina',
  Mixer: 'Mezclador',
  'Mixing Bowl': 'Bol para mezclar',
  Moat: 'Foso',
  'Mobile Home': 'Casa móvil',
  'Mobile Phone': 'Teléfono móvil',
  'Model T': 'Modelo T',
  Modem: 'Módem',
  'Modern Art': 'Arte Moderno',
  Mojito: 'Mojitos',
  Mold: 'Molde',
  Mole: 'Topo',
  Monarch: 'Monarca',
  Monastery: 'Monasterio',
  Money: 'Dinero',
  Monitor: 'Monitor',
  Monk: 'Monje',
  Monkey: 'Mono',
  Monorail: 'Monocarril',
  Monument: 'Monumento',
  Moon: 'Luna',
  Moose: 'Alce',
  Moped: 'Ciclomotor',
  Mortar: 'Mortero',
  Mosaic: 'Mosaico',
  Mosque: 'Mezquita',
  'Mosquito Net': 'Mosquitero',
  Mosquito: 'Mosquito',
  Moss: 'Musgo',
  Motel: 'Motel',
  Moth: 'Polilla',
  Motocross: 'Motocrós',
  'Motor Scooter': 'Motor de scooter',
  Motor: 'Motor',
  Motorcycle: 'Motocicleta',
  Mound: 'Montículo',
  'Mountain Bike': 'Bicicleta de montaña',
  'Mountain Goat': 'Cabra de montaña',
  'Mountain Range': 'Cordillera',
  'Mountain Tent': 'Tienda de montaña',
  Mountain: 'Montaña',
  Mouse: 'Ratón',
  Mousepad: 'Alfombrilla de ratón',
  Mouth: 'Boca',
  'Moving Van': 'Van en movimiento',
  Mud: 'Barro',
  Muffin: 'Mollete',
  'Mullet Fish': 'Pescado salmonete',
  Mural: 'Mural',
  Museum: 'Museo',
  Mushroom: 'Champiñón',
  'Music Band': 'Grupo de música',
  'Musical Instrument': 'Instrumento musical',
  Musician: 'Músico',
  Mustache: 'Bigote',
  Mustang: 'Mustango',
  Mustard: 'Mostaza',
  Nachos: 'Nachos',
  Nail: 'Clavo',
  Napkin: 'Servilleta',
  Nature: 'Naturaleza',
  Navel: 'Ombligo',
  Navy: 'Armada',
  Nebula: 'Nebulosa',
  Neck: 'Cuello',
  Necklace: 'Collar',
  Necktie: 'Corbata',
  Neighborhood: 'Barrio',
  Neon: 'Neón',
  Nest: 'Nido',
  Network: 'Red',
  Newborn: 'Recién nacido',
  Newfoundland: 'Terranova',
  Newspaper: 'Periódico',
  Newsstand: 'Puesto de periódicos',
  Nickel: 'Níquel',
  'Night Club': 'Pub nocturno',
  'Night Life': 'Vida nocturna',
  Night: 'Noche',
  Ninja: 'Ninja',
  Noodle: 'Fideos',
  Novel: 'Novedoso',
  Nuclear: 'Nuclear',
  Nuggets: 'Pepitas',
  Number: 'Número',
  Nurse: 'Enfermero',
  Nursery: 'Guardería',
  Nut: 'Tuerca',
  Nutcracker: 'Cascanueces',
  Oak: 'Roble',
  Oars: 'Remos',
  Oatmeal: 'Avena',
  Obelisk: 'Obelisco',
  Oboe: 'Oboe',
  Observatory: 'Observatorio',
  Ocean: 'Océano',
  Ocelot: 'Ocelote',
  Octopus: 'Pulpo',
  'Office Building': 'Edificio de oficinas',
  Office: 'Oficina',
  Officer: 'Oficial',
  Offroad: 'Fuera del camino',
  'Oil Spill': 'Derrame de petróleo',
  Oilfield: 'Yacimiento petrolífero',
  Okra: 'Okra',
  Onion: 'Cebolla',
  Opal: 'Ópalo',
  'Opera House': 'Teatro de la Ópera',
  'Operating Theatre': 'Quirófano',
  'Orange Juice': 'Zumo de naranja',
  Orange: 'Naranja',
  Orangutan: 'Orangután',
  Orca: 'Orca',
  'Orchestra Pit': 'Foso de orquesta',
  Orchestra: 'Orquesta',
  Orchid: 'Orquídea',
  Origami: 'Origami',
  Ornament: 'Ornamento',
  Oscilloscope: 'Osciloscopio',
  Ostrich: 'Avestruz',
  Otter: 'Nutria',
  Ottoman: 'Otomano',
  'Outdoor Play Area': 'Parque infantil al aire libre',
  Outdoors: 'Exteriores',
  'Outer Space': 'Espacio exterior',
  Outhouse: 'Anexo',
  Outrigger: 'Balancín',
  Oval: 'Oval',
  Oven: 'Horno',
  Overcoat: 'Gabardina',
  Overpass: 'Paso superior',
  Owl: 'Búho',
  Ox: 'Buey',
  Oyster: 'Ostra',
  'Package Delivery': 'Entrega de paquetes',
  Paddle: 'Paleta',
  'Paddy Field': 'Campo de arroz',
  Page: 'Página',
  Pagoda: 'Pagoda',
  'Paint Container': 'Contenedor de pintura',
  Paintball: 'Paintball',
  Painting: 'Pintura',
  Paisley: 'Cachemir',
  Pajamas: 'Pijama',
  Palace: 'Palacio',
  Palette: 'Paleta',
  'Palm Tree': 'Palmera',
  Pancake: 'Tortita',
  Panoramic: 'Panorámico',
  Pansy: 'Pensamiento',
  Panther: 'Pantera',
  Panties: 'Bragas',
  Pantry: 'Despensa',
  Pants: 'Pantalones',
  Pantyhose: 'Pantys',
  Paparazzi: 'Paparazzi',
  Papaya: 'Papaya',
  'Paper Towel': 'Toalla de papel',
  Paper: 'Papel',
  Papillon: 'Papillon',
  'Para Rubber Tree': 'Árbol de caucho para',
  Parachute: 'Paracaídas',
  Parade: 'Desfile',
  Parakeet: 'Perico',
  'Park Bench': 'Banco del parque',
  Park: 'Parque',
  'Parking Lot': 'Estacionamiento',
  'Parking Meter': 'Parquímetro',
  Parking: 'Estacionamiento',
  Parliament: 'Parlamento',
  Parrot: 'Loro',
  Parsley: 'Perejil',
  Parsnip: 'Chirivía',
  Parthenon: 'Partenón',
  Partridge: 'Perdiz',
  'Party Hat': 'Sombrero de fiesta',
  Party: 'Fiesta',
  'Passenger Car': 'Coche de pasajeros',
  Passport: 'Pasaporte',
  Pasta: 'Pasta',
  Pastry: 'Pastelería',
  Pasture: 'Pastar',
  Patchwork: 'Labor de retazos',
  Path: 'Sendero',
  Patient: 'Paciente',
  'Patio Umbrella': 'Sombrilla para patio',
  Patio: 'Patio',
  Pattern: 'Patrón',
  Pavement: 'Acera',
  Pc: 'Ordenador personal',
  Pea: 'Guisante',
  Peach: 'Durazno',
  Peacock: 'Pavo real',
  Peak: 'Cima',
  'Peanut Butter': 'Mermelada de cacahuete',
  Peanut: 'Maní',
  Pear: 'Pera',
  Pearl: 'Perla',
  Pebble: 'Guijarro',
  Pecan: 'Pacana',
  Pedal: 'Pedal',
  Pedestrian: 'Peatonal',
  Peel: 'Cáscara',
  Peeps: 'Píos',
  Pelican: 'Pelícano',
  Pen: 'Bolígrafo',
  'Pencil Box': 'Estuche',
  Pencil: 'Lápiz',
  Pendant: 'Colgante',
  Penguin: 'Pingüino',
  Peninsula: 'Península',
  Penthouse: 'Ático',
  Peony: 'Peonía',
  People: 'Gente',
  Pepper: 'Pimienta',
  Perch: 'Perca',
  Percussion: 'Percusión',
  Performer: 'Ejecutante',
  Perfume: 'Perfume',
  Pergola: 'Pérgola',
  Persimmon: 'Caqui',
  Person: 'Persona',
  Pet: 'Mascota',
  Petal: 'Pétalo',
  Petrol: 'Gasolina',
  'PEZ Dispenser': 'Dispensador PEZ',
  Pharmacy: 'Farmacia',
  Pheasant: 'Faisán',
  'Phone Booth': 'Cabina telefónica',
  Phone: 'Teléfono',
  'Photo Booth': 'Cabina de fotos',
  Photo: 'Foto',
  Photographer: 'Fotógrafo',
  Photography: 'Fotografía',
  Pianist: 'Pianista',
  Piano: 'Piano',
  Picket: 'Piquete',
  Pickle: 'Pepinillo',
  'Pickup Truck': 'Camioneta',
  Picnic: 'Picnic',
  'Picture Window': 'Ventana de imagen',
  Pie: 'Tarta',
  Pier: 'Muelle',
  Piercing: 'Perforación',
  Pig: 'Cerdo',
  Pigeon: 'Paloma',
  'Piggy Bank': 'Hucha',
  Pike: 'Lucio',
  Pill: 'Píldora',
  Pillar: 'Pilar',
  Pillow: 'Almohada',
  Pin: 'Clavo',
  Pinata: 'Piñata',
  Pine: 'Pino',
  Pineapple: 'Piña',
  'Ping Pong': 'Ping pong',
  Pipeline: 'Tubería',
  Pirate: 'Pirata',
  Piste: 'Pista',
  'Pit Stop': 'Parada en boxes',
  Pita: 'Agave',
  Pitbull: 'Pitbull',
  Pizza: 'Pizza',
  Plaid: 'Tartán',
  Plan: 'Plan',
  Planet: 'Planeta',
  Planetarium: 'Planetario',
  Plant: 'Planta',
  Planter: 'Plantador',
  Planting: 'Plantación',
  Plaque: 'Placa',
  'Plastic Bag': 'Bolsa de plastico',
  'Plastic Wrap': 'Envoltura de plástico',
  Plastic: 'Plástico',
  'Plate Rack': 'Escurreplatos',
  Plateau: 'Meseta',
  Platinum: 'Platino',
  Platter: 'Plato',
  'Play Area': 'Área de juego',
  Play: 'Jugar',
  Playground: 'Patio de recreo',
  Plaza: 'Plaza',
  Plectrum: 'Púa',
  Pliers: 'Alicates',
  Plot: 'Gráfico',
  Plug: 'Enchufar',
  Plum: 'Ciruela',
  Plumbing: 'Plomería',
  Plush: 'Felpa',
  Plywood: 'Madera contrachapada',
  Pointer: 'Puntero',
  'Polar Bear': 'Oso polar',
  'Pole Vault': 'Salto con pértiga',
  'Police Car': 'Coche de policía',
  'Police Dog': 'Perro policía',
  Police: 'Policía',
  'Polka Dot': 'Lunares',
  Pollen: 'Polen',
  Pollution: 'Contaminación',
  Polo: 'Polo',
  Pomegranate: 'Granada',
  Pomelo: 'Pomelo',
  Poncho: 'Poncho',
  'Pond Lily': 'Lirio de estanque',
  Pond: 'Estanque',
  Ponytail: 'Cola de caballo',
  Poodle: 'Caniche',
  'Pool Table': 'Mesa de billar',
  Pool: 'Piscina',
  'Pop Bottle': 'Botella de gaseosa',
  Popcorn: 'Palomitas de maiz',
  Pope: 'Papa',
  Poppy: 'Amapola',
  Porcelain: 'Porcelana',
  Porch: 'Porche',
  Porcupine: 'Puerco espín',
  Pork: 'Cerdo',
  Port: 'Puerto',
  Porthole: 'Porta',
  Portrait: 'Retrato',
  Possum: 'Zarigüeya',
  'Postage Stamp': 'Sello de correos',
  'Postal Office': 'Oficina de correos',
  Postbox: 'Buzón',
  Postcard: 'Tarjeta postal',
  Poster: 'Póster',
  Pot: 'Maceta',
  Potato: 'Papa',
  'Potted Plant': 'Planta en maceta',
  Pottery: 'Cerámica',
  Potty: 'Orinal',
  Poultry: 'Aves de corral',
  Powder: 'Polvo',
  'Power Drill': 'Taladro eléctrico',
  'Power Lines': 'Líneas eléctricas',
  'Power Plant': 'Planta de energía',
  'Prayer Beads': 'Rosario',
  Prayer: 'Oración',
  Premiere: 'Estreno',
  'Press Conference': 'Rueda de prensa',
  Pretzel: 'Galleta salada',
  Priest: 'Sacerdote',
  Printer: 'Impresora',
  Prison: 'Prisión',
  'Private Mailbox': 'Buzón Privado',
  Produce: 'Producir',
  'Projection Screen': 'Pantalla de proyección',
  Projector: 'Proyector',
  Promontory: 'Promontorio',
  Propeller: 'Hélice',
  Protest: 'Protesta',
  Ptarmigan: 'Perdiz nival',
  Pub: 'Pub',
  'Public Mailbox': 'Buzón Público',
  Puddle: 'Charco',
  Puffer: 'Fumador',
  Puffin: 'Frailecillo',
  Pug: 'Doguillo',
  Pump: 'Bomba',
  Pumpkin: 'Calabaza',
  Puppy: 'Cachorro',
  Purple: 'Púrpura',
  Purse: 'Bolso',
  Putter: 'Holgazanear',
  Pyramid: 'Pirámide',
  'QR Code': 'Código QR',
  Quail: 'Codorniz',
  Quartz: 'Cuarzo',
  Quilt: 'Colcha',
  Quince: 'Membrillo',
  Quiver: 'Carcaj',
  Rabbit: 'Conejo',
  Raccoon: 'Mapache',
  'Race Car': 'Coche de carreras',
  Racket: 'Raqueta',
  Radiator: 'Radiador',
  'Radio Telescope': 'Radio telescopio',
  Radio: 'Radio',
  Radish: 'Rábano',
  Rafting: 'Canotaje',
  Rail: 'Carril',
  Railing: 'Barandilla',
  Railway: 'Ferrocarril',
  'Rain Barrel': 'Barril de lluvia',
  Rainbow: 'Arcoíris',
  Raincoat: 'Impermeable',
  Rainforest: 'Selva',
  Raisins: 'Pasas',
  Rake: 'Rastrillo',
  Rally: 'Reunión',
  'RAM Memory': 'Memoria RAM',
  Ramp: 'Rampa',
  Ranch: 'Rancho',
  Raspberry: 'Frambuesa',
  Rat: 'Rata',
  Rattle: 'Traqueteo',
  Rattlesnake: 'Serpiente de cascabel',
  Ravioli: 'Ravioles',
  Razor: 'Maquinilla de afeitar',
  Reading: 'Leer',
  'Reception Desk': 'Recepción',
  'Reception Room': 'Sala de recepción',
  Reception: 'Recepción',
  'Recycling Symbol': 'Símbolo de reciclaje',
  'Red Carpet Premiere': 'Estreno de alfombra roja',
  'Red Carpet': 'Alfombra roja',
  'Red Cross': 'Cruz Roja',
  'Red Fox': 'Zorro rojo',
  'Red Wine': 'Vino tinto',
  'Red Wolf': 'Lobo rojo',
  Redwood: 'Secoya',
  Reed: 'Junco',
  Reef: 'Arrecife',
  Reel: 'Carrete',
  Refinery: 'Refinería',
  Refrigerator: 'Refrigerador',
  Relish: 'Saborear',
  'Remote Control': 'Control remoto',
  Reptile: 'Reptil',
  Reservoir: 'Reservorio',
  Resort: 'Complejo',
  Restaurant: 'Restaurante',
  'Revolving Door': 'Puerta giratoria',
  Rhino: 'Rinoceronte',
  Rhubarb: 'Ruibarbo',
  Ribs: 'Costillas',
  Rice: 'Arroz',
  'Riding Boot': 'Bota de montar',
  Rifle: 'Rifle',
  Ring: 'Anillo',
  Rink: 'Pista',
  Ripple: 'Onda',
  River: 'Río',
  'Road Sign': 'Señal de tráfico',
  Road: 'Carretera',
  Roast: 'Asar',
  Robe: 'Túnica',
  Robin: 'Robin',
  Robot: 'Robot',
  'Rock Beauty': 'Belleza de roca',
  'Rock Climbing': 'Escalada de roca',
  'Rock Concert': 'Concierto de rock',
  'Rock Python': 'Pitón de roca',
  Rock: 'Rock',
  Rocket: 'Cohete',
  'Rocking Chair': 'Mecedora',
  Rodent: 'Roedor',
  Rodeo: 'Rodeo',
  'Roller Coaster': 'Montaña rusa',
  'Roof Rack': 'Barra de techo',
  Roof: 'Techo',
  Room: 'Habitación',
  Rooster: 'Gallo',
  Root: 'Raíz',
  'Rope Bridge': 'Puente de cuerda',
  Rope: 'Soga',
  Rosary: 'Rosario',
  Rose: 'Rosa',
  Rotor: 'Rotor',
  Router: 'Enrutador',
  Rowboat: 'Bote de remos',
  'Rubber Eraser': 'Goma de borrar',
  Rubble: 'Escombros',
  'Rubix Cube': 'Cubo Rubix',
  Rug: 'Alfombra',
  'Rugby Ball': 'Pelota de rugby',
  Ruins: 'Restos',
  'Running Shoe': 'Zapatos para correr',
  'Running Track': 'Pista de carreras',
  Running: 'Corriendo',
  Runway: 'Pista',
  Rural: 'Rural',
  Rust: 'Óxido',
  Rutabaga: 'Nabo sueco',
  Rv: 'Autocaravana',
  Sack: 'Bolsa',
  Saddle: 'Sillín',
  Safe: 'A salvo',
  Sailboat: 'Velero',
  'Sailor Suit': 'Traje de marinero',
  'Saint Bernard': 'San Bernardo',
  Sake: 'Motivo',
  Salad: 'Ensalada',
  Salamander: 'Salamandra',
  Samurai: 'Samurai',
  Sand: 'Arena',
  Sandal: 'Sandalia',
  'Sandwich Wrap': 'Envoltura de sándwich',
  Sandwich: 'Sandwich',
  Sapphire: 'Zafiro',
  Sardine: 'Sardina',
  Sari: 'Sari',
  Sash: 'Faja',
  Saucer: 'Platillo',
  Savanna: 'Sabana',
  Saxophone: 'Saxofón',
  Scaffolding: 'Andamio',
  Scale: 'Escala',
  Scarecrow: 'Espantapájaros',
  Scarf: 'Bufanda',
  Scenery: 'Escenario',
  'School Bus': 'Autobús escolar',
  School: 'Colegio',
  Scientist: 'Científico',
  Scissors: 'Tijeras',
  Scooter: 'Scooter',
  Scoreboard: 'Marcador',
  Scorpion: 'Escorpión',
  Screen: 'Pantalla',
  Screw: 'Tornillo',
  Screwdriver: 'Destornillador',
  Scroll: 'Desplazarse',
  'Scuba Diving': 'Submarinismo',
  Sculpture: 'Escultura',
  'Sea Anemone': 'Anémona de mar',
  'Sea Life': 'Vida marina',
  'Sea Lion': 'León marino',
  'Sea Snake': 'Serpiente de mar',
  'Sea Turtle': 'Tortuga marina',
  'Sea Waves': 'Las olas del mar',
  Sea: 'Mar',
  Seafood: 'Mariscos',
  Seagull: 'Gaviota',
  Seahorse: 'Caballo de mar',
  Seal: 'Sello',
  Seaplane: 'Hidroavión',
  Seashell: 'Concha',
  Seasoning: 'Condimento',
  'Seat Belt': 'Cinturón de seguridad',
  Seaweed: 'Algas marinas',
  Security: 'Seguridad',
  Sedan: 'Sedán',
  Seed: 'Semilla',
  Seesaw: 'Balancín',
  Segway: 'Segway',
  Selfie: 'Autofoto',
  Seminar: 'Seminario',
  'Senior Citizen': 'Jubilado',
  Server: 'Servidor',
  Sesame: 'Sésamo',
  Sewer: 'Alcantarillado',
  'Sewing Machine': 'Máquina de coser',
  Sewing: 'Coser',
  Shack: 'Choza',
  Shaker: 'Criba vibradora',
  Shallot: 'Chalote',
  Shampoo: 'Champú',
  Shark: 'Tiburón',
  Shears: 'Tijeras',
  Sheep: 'Oveja',
  'Sheet Music': 'Partitura',
  Shelf: 'Estante',
  Shelter: 'Refugio',
  Shield: 'Escudo',
  Ship: 'Barco',
  'Shipping Container': 'Contenedor de envío',
  Shipwreck: 'Naufragio',
  Shirt: 'Camisa',
  'Shoe Shop': 'Tienda de zapatos',
  Shoe: 'Zapato',
  'Shooting Range': 'Rango de disparo',
  Shop: 'Tienda',
  'Shopping Bag': 'Bolsa de la compra',
  'Shopping Basket': 'Cesta de la compra',
  'Shopping Cart': 'Carrito de compras',
  'Shopping Mall': 'Centro comercial',
  Shopping: 'Compras',
  Shoreline: 'Orilla',
  Shorts: 'Pantalón corto',
  Shotgun: 'Escopeta',
  Shoulder: 'Hombro',
  Shovel: 'Pala',
  'Shower Curtain': 'Cortina de la ducha',
  'Shower Faucet': 'Grifo de ducha',
  Shower: 'Ducha',
  Shrimp: 'Camarón',
  Shrine: 'Santuario',
  Shutter: 'Obturador',
  Siamese: 'Siamés',
  Sideboard: 'Aparador',
  Sidecar: 'Sidecar',
  Sidewalk: 'Acera',
  Siding: 'Vía muerta',
  Sign: 'Señal',
  Signature: 'Firma',
  Silhouette: 'Silueta',
  Silk: 'Seda',
  Silver: 'Plata',
  'Sink Faucet': 'Grifo del fregadero',
  Sink: 'Fregadero',
  Sitting: 'Sesión',
  Skateboard: 'Patineta',
  Skating: 'Patinaje',
  Skeleton: 'Esqueleto',
  Sketch: 'Bosquejo',
  'Ski Boot': 'Bota de esquí',
  Skiing: 'Esquiar',
  Skin: 'Piel',
  Skirt: 'Falda',
  Skunk: 'Zorrillo',
  Sky: 'Cielo',
  Skylight: 'Claraboya',
  Skyscraper: 'Rascacielos',
  Slate: 'Pizarra',
  Sled: 'Trineo',
  Sleeping: 'Durmiendo',
  Sleeve: 'Manga',
  Sliced: 'Rebanado',
  Slide: 'Deslizar',
  'Sliding Door': 'Puerta corrediza',
  Slingshot: 'Honda',
  Slope: 'Pendiente',
  Slot: 'Ranura',
  Sloth: 'Perezoso',
  'Slow Cooker': 'Olla de cocción lenta',
  Slug: 'Babosa',
  Slum: 'Barrio bajo',
  Smelling: 'Oler',
  Smile: 'Sonreír',
  Smog: 'Niebla tóxica',
  'Smoke Pipe': 'Pipa de humo',
  Smoke: 'Fumar',
  Smoking: 'Esmoquin',
  Smoothie: 'Zalamero',
  Snack: 'Merienda',
  Snail: 'Caracol',
  Snake: 'Víbora',
  Sneaker: 'Zapatilla de deporte',
  Sniper: 'Francotirador',
  Snorkeling: 'Bucear',
  Snout: 'Hocico',
  'Snow Angel': 'Ángel de nieve',
  'Snow Leopard': 'Leopardo de nieve',
  Snow: 'Nieve',
  Snowboarding: 'Snowboarding',
  Snowflake: 'Copo de nieve',
  Snowman: 'Monigote de nieve',
  Snowplow: 'Quitanieves',
  Soap: 'Jabón',
  'Soccer Ball': 'Balón de fútbol',
  Soccer: 'Fútbol',
  Sock: 'Calcetín',
  Soda: 'Soda',
  Softball: 'Sofbol',
  Soil: 'Suelo',
  'Solar Panels': 'Paneles solares',
  Soldier: 'Soldado',
  Sombrero: 'Sombrero',
  'Soup Bowl': 'Tazón de sopa',
  Soup: 'Sopa',
  Soy: 'Soja',
  Spa: 'Spa',
  'Space Heater': 'Calentador',
  'Space Shuttle': 'Transbordador espacial',
  'Space Station': 'Estación Espacial',
  Space: 'Espacio',
  Spaceship: 'Astronave',
  Spaghetti: 'Espaguetis',
  Spandex: 'Spandex',
  Spaniel: 'Spaniel',
  Sparrow: 'Gorrión',
  Speaker: 'Vocero',
  Spear: 'Lanza',
  Speech: 'Habla',
  Sphere: 'Esfera',
  Spice: 'Especia',
  'Spider Web': 'Telaraña',
  Spider: 'Araña',
  Spinach: 'Espinaca',
  Spiral: 'Espiral',
  Spire: 'Capitel',
  Spoke: 'Habló',
  'Sponge Animal': 'Esponja Animal',
  Sponge: 'Esponja',
  Spoon: 'Cuchara',
  Sport: 'Deporte',
  'Sports Car': 'Coche deportivo',
  Sports: 'Deportes',
  Spotlight: 'Foco',
  'Spray Can': 'Envase de aerosol',
  'Spring Break': 'Vacaciones de primavera',
  Spring: 'Primavera',
  Sprinkler: 'Aspersor',
  Sprinkles: 'Asperja',
  Sprout: 'Brote',
  Spruce: 'Abeto',
  Squash: 'Calabaza',
  Squat: 'Ponerse en cuclillas',
  Squid: 'Calamar',
  Squirrel: 'Ardilla',
  Stadium: 'Estadio',
  Stage: 'Escenario',
  Stain: 'Mancha',
  'Stained Glass': 'Vitral',
  'Stained Wood': 'Madera Teñida',
  Staircase: 'Escalera',
  Stallion: 'Semental',
  Stand: 'Permanecer',
  Standing: 'En pie',
  'Star Symbol': 'Símbolo de estrella',
  Starfish: 'Estrella de mar',
  'Starry Sky': 'Cielo estrellado',
  Statue: 'Estatua',
  Steak: 'Bife',
  'Steam Engine': 'Máquina de vapor',
  Steamer: 'Buque de vapor',
  Steel: 'Acero',
  Steeple: 'Campanario',
  'Steering Wheel': 'Volante',
  Stein: 'Jarra',
  Stencil: 'Plantilla',
  Stereo: 'Estéreo',
  Stew: 'Estofado',
  Stick: 'Vara',
  Sticker: 'Pegatina',
  Stilts: 'Zancos',
  Stingray: 'Mantarraya',
  Stitch: 'Puntada',
  Stocking: 'Media',
  Stole: 'Robó',
  Stomach: 'Estómago',
  'Stone Wall': 'Pared de piedra',
  Stopsign: 'Señal de stop',
  Stopwatch: 'Cronógrafo',
  Stork: 'Cigüeña',
  Storm: 'Tormenta',
  Stout: 'Cerveza negra',
  Stove: 'Cocina',
  Strap: 'Correa',
  Straw: 'Sorbete',
  Strawberry: 'Fresa',
  Stream: 'Arroyo',
  Street: 'Calle',
  Streetcar: 'Tranvía',
  Stretch: 'Estirar',
  Stroller: 'Paseante',
  Student: 'Alumno',
  Studio: 'Estudio',
  Stuffing: 'Relleno',
  Sturgeon: 'Esturión',
  Submarine: 'Submarino',
  Suburb: 'Suburbio',
  Subway: 'Subterraneo',
  Suede: 'Ante',
  Sugar: 'Azúcar',
  Suit: 'Traje',
  Suitcase: 'Maleta',
  Summer: 'Verano',
  Sumo: 'Sumo',
  'Sun Hat': 'Sombrero para el sol',
  Sun: 'Sol',
  Sundial: 'Reloj de sol',
  Sunflower: 'Girasol',
  Sunglasses: 'Gafas de sol',
  Sunlight: 'Luz del sol',
  Sunrise: 'Amanecer',
  Sunscreen: 'Protector solar',
  Sunset: 'Puesta de sol',
  Supermarket: 'Supermercado',
  Supper: 'Cena',
  'Surface Computer': 'Computadora de superficie',
  Surfboard: 'Tabla de surf',
  Surfing: 'Surf',
  Surgeon: 'Cirujano',
  Surgeonfish: 'Pez cirujano',
  Surgery: 'Cirugía',
  Sushi: 'Sushi',
  Suspenders: 'Tirantes',
  'Suspension Bridge': 'Puente colgante',
  Suspension: 'Suspensión',
  Suv: 'Todoterreno',
  Swallow: 'Tragar',
  Swamp: 'Pantano',
  Swan: 'Cisne',
  'Swat Team': 'Equipo SWAT',
  Sweater: 'Suéter',
  Sweatshirt: 'Camisa de entrenamiento',
  'Sweet Potato': 'Batata',
  Sweets: 'Dulces',
  'Swimming Cap': 'Gorro de natación',
  'Swimming Pool': 'Alberca',
  Swimming: 'Nadando',
  Swimwear: 'Trajes de baño',
  Swing: 'Balancear',
  Switch: 'Cambiar',
  Sword: 'Espada',
  Swordfish: 'Pez espada',
  Sycamore: 'Sicomoro',
  Symbol: 'Símbolo',
  Syrup: 'Jarabe',
  'T-Rex': 'Tirano saurio Rex',
  'T-Shirt': 'Camiseta de manga corta',
  'Table Lamp': 'Lámpara de mesa',
  Table: 'Mesa',
  Tablecloth: 'Manteles',
  'Tablet Computer': 'Tableta',
  Tabletop: 'Mesa',
  Tabloid: 'Tabloide',
  Tachometer: 'Tacómetro',
  Taco: 'Tacos',
  Tadpole: 'Renacuajo',
  'Tai Chi': 'Tai Chi',
  Takeoff: 'Quitarse',
  'Tandem Bicycle': 'Bicicleta Tándem',
  Tango: 'Tango',
  'Tank Top': 'Camiseta sin mangas',
  Tank: 'Tanque',
  Tanker: 'Petrolero',
  Tap: 'Tocar',
  'Tape Player': 'Reproductor de casetes',
  Tape: 'Cinta',
  Tapestry: 'Tapiz',
  Tar: 'Alquitrán',
  Tarantula: 'Tarántula',
  Tarmac: 'Pista',
  Tart: 'Tarta',
  Tartan: 'Tartán',
  Tattoo: 'Tatuaje',
  Taxi: 'Taxi',
  Tea: 'Té',
  Teacher: 'Maestro',
  Teal: 'Verde azulado',
  'Team Sport': 'Equipo de deporte',
  Team: 'Equipo',
  Teapot: 'Tetera',
  'Teddy Bear': 'Oso de peluche',
  Teen: 'Adolescente',
  Teeth: 'Diente',
  Telescope: 'Telescopio',
  Television: 'Televisión',
  Temple: 'Templo',
  'Tennis Ball': 'Pelota de tenis',
  'Tennis Court': 'Pista de tenis',
  'Tennis Racket': 'Raqueta de tenis',
  Tennis: 'Tenis',
  Tent: 'Tienda',
  Tequila: 'Tequila',
  Terminal: 'Terminal',
  Termite: 'Termita',
  Terrace: 'Terraza',
  Terrier: 'Terrier',
  'Text Message': 'Mensaje de texto',
  Text: 'Texto',
  Texting: 'Mensajes de texto',
  Texture: 'Textura',
  Theater: 'Teatro',
  'Theme Park': 'Parque temático',
  Therapy: 'Terapia',
  Thigh: 'Hermético',
  Thistle: 'Cardo',
  Thong: 'Correa',
  'Three-Toed Sloth': 'Perezoso de tres dedos',
  Throat: 'Garganta',
  Throne: 'Trono',
  'Thumbs Up': 'Pulgares hacia arriba',
  Thunderstorm: 'Tormenta',
  Tiara: 'Tiara',
  Tick: 'Garrapata',
  Ticket: 'Billete',
  Tie: 'Corbata',
  Tiger: 'Tigre',
  Tights: 'Medias',
  Tiki: 'Tiki',
  'Tile Roof': 'Teja',
  Tile: 'Teja',
  Tin: 'Estaño',
  Tire: 'Neumático',
  Tissue: 'Pañuelo de papel',
  Toad: 'Sapo',
  Toast: 'Tostado',
  Toaster: 'Tostadora',
  Tobacco: 'Tabaco',
  Toe: 'Dedo del pie',
  'Toilet Paper': 'Papel higienico',
  Toilet: 'Baño',
  Tomato: 'Tomate',
  Tomb: 'Tumba',
  Tombstone: 'Lápida sepulcral',
  Tongue: 'Lengua',
  Tool: 'Herramienta',
  Toolshed: 'Cobertizo para herramientas',
  Toothbrush: 'Cepillo de dientes',
  Toothpaste: 'Pasta dental',
  Torch: 'Antorcha',
  Torii: 'Torii',
  Tornado: 'Tornado',
  Torpedo: 'Torpedo',
  Torso: 'Torso',
  Torte: 'Torta',
  Tortellini: 'Tortellini',
  Tortilla: 'Tortilla',
  Tortoise: 'Tortuga',
  'Tote Bag': 'Bolso de mano',
  Totem: 'Tótem',
  Toucan: 'Tucán',
  'Tour Bus': 'Autobús turístico',
  Tourist: 'Turista',
  'Tow Truck': 'Camión de remolque',
  Towel: 'Toalla',
  Tower: 'Torre',
  'Town Square': 'Plaza de la ciudad',
  Town: 'Pueblo',
  Towpath: 'Camino de sirga',
  Toy: 'Juguete',
  Tractor: 'Tractor',
  Trademark: 'Marca comercial',
  'Traffic Jam': 'Embotellamiento',
  'Traffic Light': 'Semáforo',
  Trail: 'Camino',
  'Trailer Truck': 'Camión de remolque',
  'Train Station': 'Estación de tren',
  'Train Track': 'Vías de tren',
  Train: 'Tren',
  Tram: 'Tranvía',
  Trampoline: 'Trampolín',
  Transportation: 'Transporte',
  'Trash Can': 'Bote de basura',
  Trash: 'Basura',
  Tray: 'Bandeja',
  'Treasure Flower': 'Flor del tesoro',
  Treasure: 'Tesoro',
  'Tree Frog': 'Rana de árbol',
  'Tree House': 'Casa de árbol',
  'Tree Stump': 'Tocón de árbol',
  'Tree Trunk': 'Tronco de arbol',
  Tree: 'Árbol',
  'Trench Coat': 'Gabardina',
  Triangle: 'Triángulo',
  Tribe: 'Tribu',
  Tricycle: 'Triciclo',
  Trident: 'Tridente',
  Tripod: 'Trípode',
  Trolley: 'Carretilla',
  Trombone: 'Trombón',
  Troop: 'Tropa',
  Trophy: 'Trofeo',
  Tropical: 'Tropical',
  Trout: 'Trucha',
  Trowel: 'Paleta',
  Truck: 'Camión',
  Trumpet: 'Trompeta',
  Tsunami: 'Tsunami',
  Tub: 'Tina',
  Tuba: 'Tuba',
  Tubing: 'Tubería',
  Tugboat: 'Remolcador',
  Tulip: 'Tulipán',
  Tuna: 'Atún',
  Tundra: 'Tundra',
  Tunnel: 'Túnel',
  Turban: 'Turbante',
  Turbine: 'Turbina',
  'Turkey Bird': 'Pavo',
  'Turkey Dinner': 'Cena de pavo',
  Turnip: 'Nabo',
  Turnstile: 'Torniquete',
  Turquoise: 'Turquesa',
  Turtle: 'Tortuga',
  Tuxedo: 'Esmoquin',
  TV: 'TELEVISOR',
  Umbrella: 'Sombrilla',
  Undershirt: 'Camiseta',
  Underwater: 'Submarino',
  Underwear: 'Ropa interior',
  Universe: 'Universo',
  'Upright Piano': 'Piano vertical',
  Urban: 'Urbano',
  Urchin: 'Pilluelo',
  Urn: 'Urna',
  'Utility Pole': 'Poste de electricidad',
  Vacation: 'Vacación',
  'Vacuum Cleaner': 'Aspiradora',
  Valley: 'Valle',
  Van: 'Camioneta',
  Vase: 'Florero',
  'Vault Ceiling': 'Techo de bóveda',
  Vegetable: 'Vegetal',
  Vegetation: 'Vegetación',
  Vehicle: 'Vehículo',
  Veil: 'Velo',
  Veins: 'Venas',
  Velvet: 'Terciopelo',
  'Vending Machine': 'Máquina expendedora',
  Vermicelli: 'Fideos',
  Vespa: 'Vespa',
  Vessel: 'Buque',
  Vest: 'Chaleco',
  Veterinarian: 'Veterinario',
  Viaduct: 'Viaducto',
  Vibraphone: 'Vibráfono',
  'Video Camera': 'Camara de video',
  'Video Gaming': 'Videojuegos',
  Vigil: 'Vigilia',
  Villa: 'Villa',
  Vine: 'Vino',
  Vineyard: 'Viñedo',
  Viola: 'Viola',
  Violin: 'Violín',
  Vise: 'Tornillo',
  Volcano: 'Volcán',
  Volleyball: 'Vóleibol',
  Vulture: 'Buitre',
  Waffle: 'Gofre',
  Wagon: 'Vagón',
  Waiter: 'Mesero',
  'Waiting Room': 'Sala de espera',
  'Walk-In Closet': 'Vestidor',
  Walking: 'Caminando',
  Walkway: 'Pasarela',
  'Wall Clock': 'Reloj de pared',
  Wall: 'Pared',
  Wallaby: 'Ualabí',
  Wallet: 'Cartera',
  Walnut: 'Nuez',
  Walrus: 'Morsa',
  Wand: 'Varita mágica',
  Wardrobe: 'Armario',
  Warehouse: 'Depósito',
  Warplane: 'Avión de guerra',
  Warthog: 'Jabalí',
  Washer: 'Lavadora',
  Washing: 'Lavado',
  Wasp: 'Avispa',
  'Water Bottle': 'Botella de agua',
  'Water Gun': 'Pistola de agua',
  'Water Jug': 'Jarra de agua',
  'Water Park': 'Parque acuatico',
  'Water Tower': 'Torre de agua',
  Water: 'Agua',
  Watercraft: 'Embarcaciones',
  Waterfall: 'Cascada',
  Waterfowl: 'Aves acuáticas',
  Waterfront: 'Costero',
  'Watering Can': 'Regadera',
  Watermelon: 'Sandía',
  'Wax Seal': 'Sello de cera',
  Weapon: 'Arma',
  Weaponry: 'Arsenal',
  Weasel: 'Comadreja',
  Weather: 'Tiempo',
  Weaving: 'Costura',
  Webcam: 'Cámara web',
  Webpage: 'Página web',
  'Wedding Cake': 'Pastel de bodas',
  'Wedding Gown': 'Vestido de boda',
  Wedding: 'Boda',
  Wedge: 'Cuña',
  Weed: 'Hierba',
  Whale: 'Ballena',
  Wheat: 'Trigo',
  Wheel: 'Rueda',
  Wheelbarrow: 'Carretilla',
  Wheelchair: 'Silla de ruedas',
  Whip: 'Látigo',
  'Whipped Cream': 'Crema batida',
  Whisky: 'Whisky',
  Whistle: 'Silbato',
  'White Board': 'Pizarron',
  'White Dog': 'Perro blanco',
  White: 'Blanco',
  Wig: 'Peluca',
  Wilderness: 'Desierto',
  Wildlife: 'Fauna silvestre',
  Willow: 'Sauce',
  'Wind Turbine': 'Turbina eólica',
  Windchime: 'Carillón de viento',
  'Window Display': 'Escaparate',
  'Window Shade': 'Persiana',
  Window: 'Ventana',
  Windshield: 'Parabrisas',
  'Wine Bottle': 'Botella de vino',
  'Wine Glass': 'Copa de vino',
  Wine: 'Vino',
  Winter: 'Invierno',
  Wire: 'Cable',
  Wiring: 'Alambrado',
  Wok: 'Wok',
  Wolf: 'Lobo',
  Woman: 'Mujer',
  Wood: 'Madera',
  'Wooden Spoon': 'Cuchara de madera',
  Woodland: 'Bosque',
  Woodpecker: 'Pájaro carpintero',
  Wool: 'Lana',
  Word: 'Palabra',
  Worker: 'Trabajador',
  'Working Out': 'Trabajando',
  Workshop: 'Taller',
  Worm: 'Gusano',
  Worship: 'Rendir culto',
  Woven: 'Tejido',
  Wreath: 'Guirnalda',
  Wren: 'Reyezuelo',
  Wrench: 'Llave inglesa',
  Wrestling: 'Lucha',
  Wrist: 'Pulsera',
  Wristwatch: 'Reloj de pulsera',
  'X-Ray': 'Radiografía',
  Xylophone: 'Xilófono',
  Yacht: 'Yate',
  Yak: 'Yak',
  Yam: 'Batata',
  Yard: 'Patio',
  Yarn: 'Hilo',
  Yew: 'Tejo',
  Yoga: 'Yoga',
  Yogurt: 'Yogur',
  'Zebra Crossing': 'Paso de cebra',
  Zebra: 'Cebra',
  Zipper: 'Cremallera',
  Zoo: 'Zoo',
  Zucchini: 'Calabacín',
}

export { labels }
